"""
DLP Analysis Dashboard — Streamlit App
Supports: intent mode JSON, fp mode JSON (generated by dlp_analysis.py)
"""

import json
from typing import Any, Dict, List, Optional

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ──────────────────────────────────────────────────────────────────────────────
# Page config
# ──────────────────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="DLP Analysis Dashboard",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────────────────────────────────────
# CSS
# ──────────────────────────────────────────────────────────────────────────────

st.markdown(
    """
    <style>
    .block-container { padding-top: 1.5rem; }

    .metric-card {
        background: #1e2130;
        border-radius: 10px;
        padding: 16px 20px;
        border-left: 4px solid #4f8ef7;
        height: 100%;
    }
    .metric-card.red   { border-left-color: #f74f4f; }
    .metric-card.amber { border-left-color: #f7a94f; }
    .metric-card.green { border-left-color: #4ff780; }
    .metric-card.blue  { border-left-color: #4f8ef7; }
    .metric-card.purple{ border-left-color: #b07fff; }
    .metric-label { font-size: 0.78rem; color: #aaa; margin-bottom: 4px; }
    .metric-value { font-size: 2rem; font-weight: 700; color: #fff; }

    .badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 20px;
        font-size: 0.75rem;
        font-weight: 600;
    }
    .badge-red    { background:#f74f4f22; color:#f74f4f; border:1px solid #f74f4f55; }
    .badge-amber  { background:#f7a94f22; color:#f7a94f; border:1px solid #f7a94f55; }
    .badge-green  { background:#4ff78022; color:#4ff780; border:1px solid #4ff78055; }
    .badge-blue   { background:#4f8ef722; color:#4f8ef7; border:1px solid #4f8ef755; }
    .badge-purple { background:#b07fff22; color:#b07fff; border:1px solid #b07fff55; }
    .badge-grey   { background:#88888822; color:#aaa;    border:1px solid #88888855; }

    .snippet-box {
        background: #0e1117;
        border: 1px solid #2a2d3e;
        border-radius: 6px;
        padding: 10px 14px;
        font-family: monospace;
        font-size: 0.82rem;
        color: #ccc;
        margin: 4px 0;
        white-space: pre-wrap;
        word-break: break-word;
    }

    .evidence-card {
        background: #1a1d2e;
        border: 1px solid #2a2d3e;
        border-radius: 8px;
        padding: 12px 16px;
        margin: 6px 0;
    }
    .evidence-card.fp  { border-left: 3px solid #f74f4f; }
    .evidence-card.tp  { border-left: 3px solid #4ff780; }
    .evidence-card.unc { border-left: 3px solid #f7a94f; }
    .evidence-entity {
        font-family: monospace;
        font-size: 0.85rem;
        font-weight: 700;
        color: #f7a94f;
        background: #f7a94f11;
        padding: 1px 6px;
        border-radius: 4px;
    }
    .evidence-subcat {
        font-size: 0.72rem;
        color: #888;
        margin-left: 6px;
    }
    .evidence-reason  { font-size: 0.83rem; color: #bbb; margin-top: 6px; }
    .evidence-snippet {
        font-family: monospace;
        font-size: 0.78rem;
        color: #888;
        margin-top: 4px;
        white-space: pre-wrap;
        word-break: break-word;
    }

    .rationale-box {
        background: #1a1d2e;
        border-left: 3px solid #4f8ef7;
        border-radius: 0 6px 6px 0;
        padding: 10px 14px;
        font-size: 0.85rem;
        color: #bbb;
        margin: 6px 0;
    }
    .rationale-box.amber { border-left-color: #f7a94f; }
    .rationale-box.red   { border-left-color: #f74f4f; }
    .rationale-box.green { border-left-color: #4ff780; }
    .rationale-box.grey  { border-left-color: #888; }

    .section-divider { border-top: 1px solid #2a2d3e; margin: 20px 0; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ──────────────────────────────────────────────────────────────────────────────
# Constants & helpers
# ──────────────────────────────────────────────────────────────────────────────

ASSESSMENT_ORDER = {"high_fp": 0, "moderate_fp": 1, "low_fp": 2, "no_fp": 3}
RISK_ORDER       = {"critical": 0, "high": 1, "medium": 2, "low": 3}

ASSESSMENT_COLORS = {
    "high_fp":     ("#f74f4f", "red"),
    "moderate_fp": ("#f7a94f", "amber"),
    "low_fp":      ("#4ff780", "green"),
    "no_fp":       ("#888888", "grey"),
}
RISK_COLORS = {
    "critical": ("#f74f4f", "red"),
    "high":     ("#f7a94f", "amber"),
    "medium":   ("#4f8ef7", "blue"),
    "low":      ("#4ff780", "green"),
}
TUNING_COLORS = {
    "disable":       "#f74f4f",
    "tighten_regex": "#f7a94f",
    "add_allowlist": "#f7a94f",
    "reduce_scope":  "#4f8ef7",
    "no_action":     "#4ff780",
}
VERDICT_CSS = {"FP": "fp", "TP": "tp", "UNCERTAIN": "unc"}


def mc(label: str, value: Any, color: str = "blue") -> str:
    return (
        f'<div class="metric-card {color}">'
        f'<div class="metric-label">{label}</div>'
        f'<div class="metric-value">{value}</div>'
        "</div>"
    )


def badge(text: str, kind: str = "grey") -> str:
    return f'<span class="badge badge-{kind}">{text}</span>'


def assessment_badge(a: Optional[str]) -> str:
    if not a:
        return badge("—", "grey")
    label = a.replace("_", " ").upper()
    _, kind = ASSESSMENT_COLORS.get(a, ("#aaa", "grey"))
    return badge(label, kind)


def risk_badge(r: Optional[str]) -> str:
    if not r:
        return badge("—", "grey")
    _, kind = RISK_COLORS.get(r, ("#aaa", "grey"))
    return badge(r.upper(), kind)


def verdict_badge(v: Optional[str]) -> str:
    m = {"FP": ("FP", "red"), "TP": ("TP", "green"), "UNCERTAIN": ("UNCERTAIN", "amber")}
    label, kind = m.get(v or "", ("—", "grey"))
    return badge(label, kind)


def rationale_box(text: Optional[str], color: str = "blue") -> str:
    if not text:
        return ""
    safe = text.replace("<", "&lt;").replace(">", "&gt;")
    return f'<div class="rationale-box {color}">{safe}</div>'


def pct(n: int, d: int) -> str:
    return "—" if d == 0 else f"{n / d * 100:.1f}%"


def load_json(uploaded) -> Optional[Dict]:
    try:
        return json.load(uploaded)
    except Exception as e:
        st.error(f"Could not parse JSON: {e}")
        return None


def _div() -> None:
    st.markdown("<div class='section-divider'></div>", unsafe_allow_html=True)


def render_evidence_card(item: Dict, show_fp_reason: bool = False) -> str:
    verdict   = item.get("verdict", "—")
    entity    = item.get("flagged_entity") or ""
    subcat    = item.get("entity_subcategory") or ""
    snippet   = (item.get("input_snippet") or "").replace("<", "&lt;").replace(">", "&gt;")
    reason_k  = "fp_reason" if show_fp_reason else "reason"
    reason    = (item.get(reason_k) or "").replace("<", "&lt;").replace(">", "&gt;")
    css       = VERDICT_CSS.get(verdict, "unc")

    entity_html = f'<span class="evidence-entity">{entity}</span>' if entity else ""
    subcat_html = f'<span class="evidence-subcat">{subcat}</span>'  if subcat else ""

    return (
        f'<div class="evidence-card {css}">'
        f'  <div>{verdict_badge(verdict)} {entity_html}{subcat_html}</div>'
        f'  <div class="evidence-snippet">{snippet}</div>'
        f'  <div class="evidence-reason">{reason}</div>'
        "</div>"
    )


# ──────────────────────────────────────────────────────────────────────────────
# Sidebar
# ──────────────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.title("🛡️ DLP Dashboard")
    st.caption("Visualise & explore DLP analysis output JSON files.")
    st.divider()

    st.subheader("Load Files")
    intent_file = st.file_uploader(
        "Intent Analysis JSON",
        type=["json"],
        key="intent_upload",
        help="dlp_intent_*.json",
    )
    fp_file = st.file_uploader(
        "False-Positive Analysis JSON",
        type=["json"],
        key="fp_upload",
        help="dlp_fp_*.json",
    )

    st.divider()
    active_tab = st.radio(
        "View",
        ["📊 Overview", "🎯 Intent Analysis", "⚠️ FP Analysis"],
        index=0,
    )

# ──────────────────────────────────────────────────────────────────────────────
# Load data
# ──────────────────────────────────────────────────────────────────────────────

intent_data: Optional[Dict] = load_json(intent_file) if intent_file else None
fp_data:     Optional[Dict] = load_json(fp_file)     if fp_file     else None

# ══════════════════════════════════════════════════════════════════════════════
# OVERVIEW TAB
# ══════════════════════════════════════════════════════════════════════════════

if active_tab == "📊 Overview":
    st.title("📊 DLP Analysis Overview")

    if not intent_data and not fp_data:
        st.info("Upload one or both JSON files using the sidebar to get started.")
        st.stop()

    src        = intent_data or fp_data
    s          = src["summary"]
    tenant_id  = src.get("tenant_id", "—")
    generated  = (src.get("generated_at") or "—")[:10]
    total      = s.get("total_messages", 0)
    detected   = s.get("messages_with_existing_detection") or s.get("messages_with_detection", 0)
    undetected = s.get("messages_without_detection", 0)

    st.caption(f"Tenant: `{tenant_id}` · Generated: `{generated}`")

    # Top-line numbers
    c0, c1, c2, c3 = st.columns(4)
    c0.markdown(mc("Total Messages", f"{total:,}",      "blue"),  unsafe_allow_html=True)
    c1.markdown(mc("Detected",       f"{detected:,}",   "amber"), unsafe_allow_html=True)
    c2.markdown(mc("Undetected",     f"{undetected:,}", "blue"),  unsafe_allow_html=True)
    c3.markdown(mc("Detection Rate", pct(detected, total), "blue"), unsafe_allow_html=True)

    _div()
    left, right = st.columns(2)

    with left:
        st.subheader("Message Distribution")
        fig = go.Figure(go.Pie(
            labels=["Detected", "Undetected"],
            values=[detected, undetected],
            hole=0.55,
            marker_colors=["#f7a94f", "#4f8ef7"],
            textinfo="label+percent",
        ))
        fig.update_layout(
            paper_bgcolor="rgba(0,0,0,0)", font_color="#ccc",
            showlegend=False, margin=dict(t=10, b=10, l=10, r=10), height=270,
        )
        st.plotly_chart(fig, use_container_width=True)

    with right:
        if intent_data:
            st.subheader("Intent Summary")
            is_ = intent_data["summary"]
            ci1, ci2 = st.columns(2)
            ci1.metric("Clusters Analyzed",  is_.get("clusters_analyzed", "—"))
            ci2.metric("Sensitive Clusters", is_.get("sensitive_clusters_found", "—"))
        if fp_data:
            st.subheader("FP Summary")
            fs = fp_data["summary"]
            cf1, cf2, cf3 = st.columns(3)
            cf1.metric("Categories Analyzed",    fs.get("categories_analyzed", "—"))
            cf2.metric("High-FP Categories",     fs.get("high_fp_categories", "—"))
            cf3.metric("Moderate-FP Categories", fs.get("moderate_fp_categories", "—"))

    # Existing detections bar
    if intent_data and intent_data.get("existing_detections"):
        _div()
        st.subheader("Existing Detection Model Distribution")
        ed    = intent_data["existing_detections"]
        df_ed = (
            pd.DataFrame({"Model": list(ed.keys()), "Count": list(ed.values())})
            .sort_values("Count", ascending=False)
        )
        fig2 = px.bar(
            df_ed, x="Count", y="Model", orientation="h",
            color="Count",
            color_continuous_scale=["#4f8ef7", "#f7a94f", "#f74f4f"],
            labels={"Count": "Detections", "Model": ""},
            height=max(360, len(df_ed) * 18),
        )
        fig2.update_layout(
            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
            font_color="#ccc", coloraxis_showscale=False,
            margin=dict(t=10, b=10, l=10, r=10), yaxis=dict(autorange="reversed"),
        )
        fig2.update_traces(marker_line_width=0)
        st.plotly_chart(fig2, use_container_width=True)

    # FP assessment mix
    if fp_data and fp_data.get("all_category_results"):
        _div()
        cr = fp_data["all_category_results"]
        col_a, col_b = st.columns(2)
        with col_a:
            st.subheader("FP Assessment Breakdown")
            ac = pd.Series([r.get("overall_assessment", "—") for r in cr]).value_counts()
            fig3 = px.bar(
                x=ac.index, y=ac.values,
                color=ac.index,
                color_discrete_map={a: ASSESSMENT_COLORS.get(a, ("#aaa","grey"))[0] for a in ac.index},
                labels={"x": "Assessment", "y": "Categories"}, height=250,
            )
            fig3.update_layout(
                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                font_color="#ccc", showlegend=False, margin=dict(t=10, b=10, l=10, r=10),
            )
            st.plotly_chart(fig3, use_container_width=True)
        with col_b:
            st.subheader("Tuning Recommendations")
            tc = pd.Series([r.get("tuning_recommendation", "—") for r in cr]).value_counts()
            fig4 = px.bar(
                x=tc.index, y=tc.values,
                color=tc.index, color_discrete_map=TUNING_COLORS,
                labels={"x": "", "y": "Categories"}, height=250,
            )
            fig4.update_layout(
                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                font_color="#ccc", showlegend=False, margin=dict(t=10, b=10, l=10, r=10),
            )
            st.plotly_chart(fig4, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# INTENT ANALYSIS TAB
# ══════════════════════════════════════════════════════════════════════════════

elif active_tab == "🎯 Intent Analysis":
    st.title("🎯 Intent Analysis")

    if not intent_data:
        st.info("Upload an Intent Analysis JSON file using the sidebar.")
        st.stop()

    s        = intent_data["summary"]
    models   = intent_data.get("suggested_new_models", [])
    clusters = intent_data.get("all_cluster_results", [])

    # Metrics
    c0, c1, c2, c3, c4 = st.columns(5)
    c0.markdown(mc("Total Messages",      f"{s.get('total_messages',0):,}", "blue"),  unsafe_allow_html=True)
    c1.markdown(mc("Existing Detections", f"{s.get('messages_with_existing_detection',0):,}", "amber"), unsafe_allow_html=True)
    c2.markdown(mc("Undetected",          f"{s.get('messages_without_detection',0):,}", "blue"),  unsafe_allow_html=True)
    c3.markdown(mc("Clusters Analyzed",   s.get("clusters_analyzed","—"), "blue"),   unsafe_allow_html=True)
    c4.markdown(mc("Sensitive Found",     s.get("sensitive_clusters_found","—"), "red"), unsafe_allow_html=True)

    _div()

    # Filters
    fc1, fc2, fc3 = st.columns([2, 2, 3])
    risk_filter = fc1.multiselect(
        "Risk Level",
        ["critical", "high", "medium", "low"],
        default=["critical", "high", "medium", "low"],
    )
    min_conf = fc2.slider("Min Confidence", 0.0, 1.0, 0.0, 0.05)
    search   = fc3.text_input("Search intent / category / keyword", "")

    shown = [
        m for m in models
        if m.get("risk_level") in risk_filter
        and (m.get("confidence") or 0) >= min_conf
        and (
            not search
            or search.lower() in (m.get("intent_name") or "").lower()
            or search.lower() in (m.get("intent_category") or "").lower()
            or any(search.lower() in kw.lower() for kw in (m.get("top_keywords") or []))
        )
    ]

    lc, rc = st.columns([3, 2])
    with lc:
        st.subheader(f"Suggested New DLP Models ({len(shown)} shown)")
    with rc:
        if models:
            rv = pd.Series([m.get("risk_level","—") for m in models]).value_counts()
            fig_r = px.pie(
                names=rv.index, values=rv.values,
                color=rv.index,
                color_discrete_map={k: v[0] for k, v in RISK_COLORS.items()},
                hole=0.5, height=180,
            )
            fig_r.update_layout(
                paper_bgcolor="rgba(0,0,0,0)", font_color="#ccc",
                showlegend=True, margin=dict(t=5, b=5, l=5, r=5),
                legend=dict(font_size=11),
            )
            st.plotly_chart(fig_r, use_container_width=True)

    if not shown:
        st.warning("No suggested models match the current filters.")
    else:
        for m in sorted(shown, key=lambda x: RISK_ORDER.get(x.get("risk_level","low"), 3)):
            msg_count = m.get("message_count_in_cluster", 0)
            conf_pct  = round((m.get("confidence") or 0) * 100)
            with st.expander(
                f"#{m.get('rank','?')}  **{m.get('intent_name','(unnamed)')}**"
                f"  · {(m.get('risk_level') or '?').upper()}"
                f"  · {msg_count} messages",
                expanded=False,
            ):
                ml, mr = st.columns([3, 1])
                with ml:
                    st.markdown(
                        f"{risk_badge(m.get('risk_level'))} "
                        f"{badge('Confidence: ' + str(conf_pct) + '%', 'blue')} "
                        f"{badge(m.get('intent_category') or '—', 'grey')}",
                        unsafe_allow_html=True,
                    )
                    st.markdown(f"**Description:** {m.get('intent_description') or '—'}")
                    st.markdown(f"**Suggested DLP Model:** `{m.get('suggested_dlp_model') or '—'}`")
                    st.markdown(f"**Rationale:** {m.get('rationale') or '—'}")
                with mr:
                    dr = m.get("date_range") or {}
                    st.markdown(f"**Cluster ID:** `{m.get('cluster_id','—')}`")
                    st.markdown(f"**Messages:** {msg_count}")
                    if dr.get("from"):
                        st.markdown(f"**From:** {str(dr['from'])[:10]}")
                    if dr.get("to"):
                        st.markdown(f"**To:** {str(dr['to'])[:10]}")

                kw = m.get("top_keywords") or []
                if kw:
                    st.markdown("**Top Keywords:** " + "  ".join(f"`{k}`" for k in kw))

                _div()

                # ── NEW: Confidence rationale + Risk rationale ─────────────────
                rat_l, rat_r = st.columns(2)
                with rat_l:
                    conf_rat = m.get("confidence_rationale")
                    if conf_rat:
                        st.markdown("**🔍 Confidence Rationale**")
                        st.markdown(rationale_box(conf_rat, "blue"), unsafe_allow_html=True)
                with rat_r:
                    risk_rat = m.get("risk_rationale")
                    if risk_rat:
                        st.markdown("**⚡ Risk Rationale**")
                        st.markdown(rationale_box(risk_rat, "amber"), unsafe_allow_html=True)

                # ── NEW: Evidence messages ─────────────────────────────────────
                evidence = m.get("evidence_messages") or []
                if evidence:
                    st.markdown(f"**📌 Evidence Messages** ({len(evidence)} verbatim excerpts from the cluster)")
                    for ev in evidence:
                        safe_ev = ev.replace("<", "&lt;").replace(">", "&gt;")
                        st.markdown(f'<div class="snippet-box">{safe_ev}</div>', unsafe_allow_html=True)

                _div()

                # ── Triggering / counter phrase tabs ──────────────────────────
                t1, t2 = st.tabs(["✅ Triggering Phrases", "🚫 Counter Phrases"])
                with t1:
                    triggers = m.get("example_triggers") or m.get("example_triggering_phrases") or []
                    for ph in triggers:
                        safe = ph.replace("<", "&lt;").replace(">", "&gt;")
                        st.markdown(f'<div class="snippet-box">{safe}</div>', unsafe_allow_html=True)
                    if not triggers:
                        st.caption("No triggering phrases provided.")
                with t2:
                    counters = m.get("example_counters") or m.get("example_counter_phrases") or []
                    for ph in counters:
                        safe = ph.replace("<", "&lt;").replace(">", "&gt;")
                        st.markdown(f'<div class="snippet-box">{safe}</div>', unsafe_allow_html=True)
                    if not counters:
                        st.caption("No counter phrases provided.")

    # All clusters table
    _div()
    st.subheader("All Cluster Results")
    if clusters:
        df_cl = pd.DataFrame([{
            "Cluster ID":  c.get("cluster_id", "—"),
            "Sensitive":   "✅" if c.get("is_sensitive") else "❌",
            "Risk Level":  (c.get("risk_level") or "—").upper(),
            "Confidence":  f"{c.get('sensitivity_confidence', 0):.0%}",
            "Intent Name": c.get("intent_name") or "—",
            "Category":    c.get("detected_intent_category") or "—",
            "Messages":    c.get("message_count", "—"),
            "DLP Model":   c.get("suggested_dlp_model") or "—",
        } for c in clusters])
        st.dataframe(df_cl, use_container_width=True, hide_index=True, height=400)


# ══════════════════════════════════════════════════════════════════════════════
# FP ANALYSIS TAB
# ══════════════════════════════════════════════════════════════════════════════

elif active_tab == "⚠️ FP Analysis":
    st.title("⚠️ False-Positive Analysis")

    if not fp_data:
        st.info("Upload a False-Positive Analysis JSON file using the sidebar.")
        st.stop()

    s  = fp_data["summary"]
    ar = fp_data.get("action_required", [])
    cr = fp_data.get("all_category_results", [])

    # Metrics
    c0, c1, c2, c3, c4, c5 = st.columns(6)
    c0.markdown(mc("Total Messages", f"{s.get('total_messages',0):,}", "blue"),  unsafe_allow_html=True)
    c1.markdown(mc("Detected",       f"{s.get('messages_with_detection',0):,}", "amber"), unsafe_allow_html=True)
    c2.markdown(mc("Undetected",     f"{s.get('messages_without_detection',0):,}", "blue"), unsafe_allow_html=True)
    c3.markdown(mc("Categories",     s.get("categories_analyzed","—"), "blue"),   unsafe_allow_html=True)
    c4.markdown(mc("High FP",        s.get("high_fp_categories","—"), "red"),    unsafe_allow_html=True)
    c5.markdown(mc("Moderate FP",    s.get("moderate_fp_categories","—"), "amber"), unsafe_allow_html=True)

    _div()

    # 3-up charts
    ch1, ch2, ch3 = st.columns(3)
    with ch1:
        st.subheader("Assessment Mix")
        ac = pd.Series([r.get("overall_assessment","—") for r in cr]).value_counts()
        fig_a = go.Figure(go.Pie(
            labels=ac.index, values=ac.values, hole=0.5,
            marker_colors=[ASSESSMENT_COLORS.get(a, ("#aaa","grey"))[0] for a in ac.index],
        ))
        fig_a.update_layout(
            paper_bgcolor="rgba(0,0,0,0)", font_color="#ccc",
            margin=dict(t=10,b=10,l=10,r=10), height=220, legend=dict(font_size=11),
        )
        st.plotly_chart(fig_a, use_container_width=True)

    with ch2:
        st.subheader("Tuning Recommendations")
        tc = pd.Series([r.get("tuning_recommendation","—") for r in cr]).value_counts()
        fig_t = px.bar(
            x=tc.index, y=tc.values,
            color=tc.index, color_discrete_map=TUNING_COLORS,
            labels={"x":"","y":""}, height=220,
        )
        fig_t.update_layout(
            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
            font_color="#ccc", showlegend=False, margin=dict(t=10,b=10,l=10,r=10),
        )
        st.plotly_chart(fig_t, use_container_width=True)

    with ch3:
        st.subheader("Risk of Disabling")
        rc_ = pd.Series([r.get("risk_of_disabling","—") for r in cr]).value_counts()
        fig_rd = px.bar(
            x=rc_.values, y=rc_.index, orientation="h",
            color=rc_.index,
            color_discrete_map={"low":"#4ff780","medium":"#f7a94f","high":"#f74f4f","—":"#aaa"},
            labels={"x":"","y":""}, height=220,
        )
        fig_rd.update_layout(
            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
            font_color="#ccc", showlegend=False, margin=dict(t=10,b=10,l=10,r=10),
        )
        st.plotly_chart(fig_rd, use_container_width=True)

    # FP rate scatter
    st.subheader("FP Rate vs. Total Detections (per Category)")
    df_sc = pd.DataFrame([{
        "Category":         (r.get("detection_category") or r.get("category") or "—").strip(),
        "FP Rate":          r.get("estimated_fp_rate", 0),
        "Total Detections": r.get("total_detections_in_period") or r.get("total_detections") or 0,
        "Assessment":       r.get("overall_assessment", "—"),
        "Confidence":       max(r.get("fp_rate_confidence", 0.1), 0.1),
    } for r in cr])
    fig_s = px.scatter(
        df_sc, x="Total Detections", y="FP Rate",
        color="Assessment", size="Confidence", hover_name="Category",
        color_discrete_map={a: ASSESSMENT_COLORS.get(a,("#aaa","grey"))[0] for a in df_sc["Assessment"].unique()},
        labels={"FP Rate":"Estimated FP Rate"}, height=350,
    )
    fig_s.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font_color="#ccc", margin=dict(t=10,b=10,l=10,r=10), legend=dict(font_size=11),
    )
    fig_s.update_xaxes(gridcolor="#2a2d3e")
    fig_s.update_yaxes(gridcolor="#2a2d3e", tickformat=".0%")
    st.plotly_chart(fig_s, use_container_width=True)

    _div()

    # ── Action-required table ─────────────────────────────────────────────────
    st.subheader("Action-Required Categories")
    f1, f2, f3 = st.columns([2, 2, 3])
    ass_filter = f1.multiselect(
        "Assessment", ["high_fp","moderate_fp","low_fp","no_fp"],
        default=["high_fp","moderate_fp"],
    )
    tune_filter = f2.multiselect(
        "Tuning Recommendation",
        ["disable","tighten_regex","add_allowlist","reduce_scope","no_action"],
        default=[],
    )
    cat_search = f3.text_input("Search category", "")

    filtered_ar = [
        r for r in ar
        if r.get("assessment") in ass_filter
        and (not tune_filter or r.get("tuning_recommendation") in tune_filter)
        and (not cat_search or cat_search.lower() in (r.get("category") or "").lower())
    ]
    st.caption(f"Showing {len(filtered_ar)} of {len(ar)} action-required categories.")

    if filtered_ar:
        df_ar = pd.DataFrame([{
            "Rank":          r.get("rank","—"),
            "Category":      (r.get("category") or "—").strip(),
            "Assessment":    r.get("assessment","—"),
            "FP Rate":       f"{r.get('estimated_fp_rate',0):.0%}",
            "FP Confidence": f"{r.get('fp_rate_confidence',0):.0%}",
            "Total Det.":    r.get("total_detections", 0),
            "Est. TP":       r.get("estimated_tp_total", 0),
            "Est. FP":       r.get("estimated_fp_total", 0),
            "Tuning":        r.get("tuning_recommendation","—"),
            "Risk Disable":  r.get("risk_of_disabling","—"),
            "Det. Type":     r.get("detection_type","—"),
        } for r in filtered_ar])
        st.dataframe(df_ar, use_container_width=True, hide_index=True, height=300)

    _div()

    # ─────────────────────────────────────────────────────────────────────────
    # CATEGORY DRILLDOWN
    # ─────────────────────────────────────────────────────────────────────────
    st.subheader("🔎 Category Drilldown")
    st.caption("Full detail: evidence, verdicts, rationale and allowlist for each category.")

    # Sort selectbox so high_fp categories appear first
    cat_options = sorted(
        [(r.get("detection_category") or "—").strip() for r in cr],
        key=lambda x: ASSESSMENT_ORDER.get(
            next(
                (r.get("overall_assessment","no_fp") for r in cr
                 if (r.get("detection_category") or "").strip() == x),
                "no_fp",
            ), 4
        ),
    )
    selected_cat = st.selectbox("Select category", cat_options)
    cat_result   = next(
        (r for r in cr if (r.get("detection_category") or "").strip() == selected_cat), None
    )

    if cat_result:
        fp_rate_str = f"{cat_result.get('estimated_fp_rate', 0):.0%}"
        conf_str    = f"{cat_result.get('fp_rate_confidence', 0):.0%}"
        risk_str    = cat_result.get("risk_of_disabling") or "—"
        det_type    = cat_result.get("dominant_detection_type") or "—"

        st.markdown(
            f"{assessment_badge(cat_result.get('overall_assessment'))} "
            f"{badge('FP Rate: ' + fp_rate_str, 'red')} "
            f"{badge('Confidence: ' + conf_str, 'blue')} "
            f"{badge('Risk of Disabling: ' + risk_str, 'grey')} "
            f"{badge('Detection Type: ' + det_type, 'purple')}",
            unsafe_allow_html=True,
        )

        top_l, top_r = st.columns([2, 1])

        with top_l:
            st.markdown(f"**Pattern Summary:** {cat_result.get('fp_pattern_summary') or '—'}")
            st.markdown(f"**Tuning Recommendation:** `{cat_result.get('tuning_recommendation') or '—'}`")
            st.markdown(f"**Tuning Rationale:** {cat_result.get('tuning_rationale') or '—'}")

            # NEW: FP Rate Rationale
            fp_rat = cat_result.get("fp_rate_rationale")
            if fp_rat:
                st.markdown("**📊 FP Rate Rationale**")
                st.markdown(rationale_box(fp_rat, "red"), unsafe_allow_html=True)

            # NEW: Assessment Rationale
            ass_rat = cat_result.get("assessment_rationale")
            if ass_rat:
                st.markdown("**🏷️ Assessment Rationale**")
                _ac = {"high_fp":"red","moderate_fp":"amber","low_fp":"green","no_fp":"grey"}
                st.markdown(
                    rationale_box(ass_rat, _ac.get(cat_result.get("overall_assessment","no_fp"),"blue")),
                    unsafe_allow_html=True,
                )

        with top_r:
            td = cat_result.get("total_detections_in_period", 0)
            tp = cat_result.get("estimated_tp_count_total", 0)
            fp = cat_result.get("estimated_fp_count_total", 0)
            st.metric("Total Detections", td)
            mc1, mc2 = st.columns(2)
            mc1.metric("Est. TP", tp)
            mc2.metric("Est. FP", fp)
            if td > 0:
                fig_mini = go.Figure(go.Pie(
                    labels=["TP","FP"], values=[max(tp,0), max(fp,0)],
                    hole=0.5, marker_colors=["#4ff780","#f74f4f"],
                    textinfo="label+percent",
                ))
                fig_mini.update_layout(
                    paper_bgcolor="rgba(0,0,0,0)", font_color="#ccc",
                    margin=dict(t=5,b=5,l=5,r=5), height=160, showlegend=False,
                )
                st.plotly_chart(fig_mini, use_container_width=True)

        _div()

        # ── NEW: Key FP Evidence ──────────────────────────────────────────────
        key_fp = cat_result.get("key_fp_evidence") or []
        if key_fp:
            st.markdown(
                f"**🔑 Key FP Evidence** "
                f"<span style='color:#888;font-size:0.85rem'>"
                f"— {len(key_fp)} representative example(s) that drove the assessment</span>",
                unsafe_allow_html=True,
            )
            for item in key_fp:
                st.markdown(render_evidence_card(item, show_fp_reason=True), unsafe_allow_html=True)

        _div()

        # ── Allowlist patterns ────────────────────────────────────────────────
        allowlist = cat_result.get("suggested_allowlist_patterns") or []
        if allowlist:
            st.markdown(f"**🛡️ Suggested Allowlist Patterns** ({len(allowlist)})")
            for pat in allowlist:
                safe_pat = pat.replace("<", "&lt;").replace(">", "&gt;")
                st.markdown(f'<div class="snippet-box">{safe_pat}</div>', unsafe_allow_html=True)

        # ── Per-example verdicts ──────────────────────────────────────────────
        verdicts = cat_result.get("per_example_verdicts") or []
        if verdicts:
            fp_n  = sum(1 for v in verdicts if v.get("verdict") == "FP")
            tp_n  = sum(1 for v in verdicts if v.get("verdict") == "TP")
            unc_n = sum(1 for v in verdicts if v.get("verdict") == "UNCERTAIN")
            st.markdown(
                f"**📋 Per-Example Verdicts** — {len(verdicts)} samples &nbsp;"
                f"{badge(str(fp_n) + ' FP', 'red')} "
                f"{badge(str(tp_n) + ' TP', 'green')} "
                f"{badge(str(unc_n) + ' Uncertain', 'amber')}",
                unsafe_allow_html=True,
            )

            view_mode = st.radio(
                "Display verdicts as",
                ["Cards", "Table"],
                horizontal=True,
                key=f"vmode_{selected_cat}",
            )

            if view_mode == "Cards":
                for item in verdicts:
                    st.markdown(render_evidence_card(item, show_fp_reason=False), unsafe_allow_html=True)
            else:
                # Table view — now includes NEW flagged_entity + entity_subcategory columns
                df_v = pd.DataFrame([{
                    "Snippet":       (v.get("input_snippet") or "—")[:100],
                    "Flagged Entity": v.get("flagged_entity") or "—",   # NEW
                    "Subcategory":   v.get("entity_subcategory") or "—", # NEW
                    "Verdict":       v.get("verdict") or "—",
                    "Reason":        v.get("reason") or "—",
                } for v in verdicts])
                st.dataframe(
                    df_v.style.applymap(
                        lambda val: (
                            "color: #f74f4f; font-weight:bold" if val == "FP"
                            else "color: #4ff780; font-weight:bold" if val == "TP"
                            else "color: #f7a94f" if val == "UNCERTAIN"
                            else ""
                        ),
                        subset=["Verdict"],
                    ),
                    use_container_width=True,
                    hide_index=True,
                    height=min(60 + len(df_v) * 38, 520),
                )

    _div()

    # ── Full results table ────────────────────────────────────────────────────
    with st.expander("📋 Full Category Results Table (all categories)"):
        df_full = pd.DataFrame([{
            "Category":             (r.get("detection_category") or "—").strip(),
            "Assessment":           r.get("overall_assessment","—"),
            "FP Rate":              f"{r.get('estimated_fp_rate',0):.0%}",
            "FP Confidence":        f"{r.get('fp_rate_confidence',0):.0%}",
            "Total Det.":           r.get("total_detections_in_period", 0),
            "Est. TP":              r.get("estimated_tp_count_total", 0),
            "Est. FP":              r.get("estimated_fp_count_total", 0),
            "Sample TP":            r.get("estimated_tp_count_in_sample", 0),
            "Sample FP":            r.get("estimated_fp_count_in_sample", 0),
            "Tuning":               r.get("tuning_recommendation","—"),
            "Risk of Disable":      r.get("risk_of_disabling","—"),
            "FP Rate Rationale":    (r.get("fp_rate_rationale") or "")[:120],   # NEW
            "Assessment Rationale": (r.get("assessment_rationale") or "")[:120], # NEW
            "Heuristic Prior":      f"{r.get('mean_heuristic_fp_prior',0):.2f}",
            "Detection Type":       r.get("dominant_detection_type","—"),
        } for r in sorted(cr, key=lambda x: ASSESSMENT_ORDER.get(x.get("overall_assessment","no_fp"), 4))])
        st.dataframe(df_full, use_container_width=True, hide_index=True)


# ──────────────────────────────────────────────────────────────────────────────
# Footer
# ──────────────────────────────────────────────────────────────────────────────

st.markdown(
    "<hr style='border-color:#2a2d3e;margin-top:40px'/>"
    "<div style='text-align:center;color:#555;font-size:0.75rem;padding-bottom:10px'>"
    "DLP Analysis Dashboard · dlp_analysis.py"
    "</div>",
    unsafe_allow_html=True,
)